services:
  app:
    image: frontend
    container_name: frontend # This will name the container hello-front-dev
  server:
    image: backend
    container_name: backend # This will name the container hello-front-dev
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server